# **NumPy Library**

In [ ]:
import numpy as np

# **Creating An Array**

In [ ]:
x=np.array([2,3,'n',5])
print(x)
print(type(x))

['2' '3' 'n' '5']
<class 'numpy.ndarray'>


# Generating Arrays using **linspace()**

In [ ]:
b=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=False)
print(b)
c=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=True)
print(c)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


#Generating Arrays using **arange()**

In [ ]:
c=np.arange(start=1,stop=20,step=2)
print(c)

[ 1  3  5  7  9 11 13 15 17 19]



#Generating Arrays using **ones()** & **zeros()**

In [ ]:
d=np.ones(shape=(2,3), dtype=int)
print(d)
e=np.zeros(shape=(3,4))
print(e)

[[1 1 1]
 [1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



#Generating Arrays using **random.rand()**

In [ ]:
f=np.random.rand(5)
print(f)
g=np.random.rand(5,2)
print(g)

[0.40048999 0.4693604  0.27814048 0.50506672 0.85986034]
[[0.24201749 0.57931219]
 [0.34716382 0.3237869 ]
 [0.09373743 0.61434077]
 [0.33587429 0.5058871 ]
 [0.23766427 0.73128384]]


#Using **logspace()**

In [ ]:
h=np.logspace(1,20,10,True,base=10,dtype=float)
print(h)

[1.00000000e+01 1.29154967e+03 1.66810054e+05 2.15443469e+07
 2.78255940e+09 3.59381366e+11 4.64158883e+13 5.99484250e+15
 7.74263683e+17 1.00000000e+20]


#**Reshaping an Array**

In [ ]:
x=np.arange(start=1,stop=10)
print(x)
y=np.arange(start=1,stop=10).reshape(3,3)
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#**Array Dimensions**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


#**Mathematical  Operations**

#**Addition**

In [ ]:
y=np.arange(start=1,stop=10).reshape(3,3)
print(y)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

c=np.add(y,a)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#**Multiplication**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
y=np.arange(start=1,stop=10).reshape(3,3)
print(y)

d=np.multiply(y,a)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


#**Transpose**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.transpose(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#**append()**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
new_a=np.append(a,[[10,11,12]],axis=0)
print(new_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#**insert()**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.insert(a,1,[[4,8,7]],axis=0)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 8 7]
 [4 5 6]
 [7 8 9]]


#**delete()**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a_del=np.delete(a,1,axis=0)
print(a_del)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


#**Creating Matrix**

In [ ]:
a=np.matrix("1,2,3;4,5,6;7,8,9")
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#**shape()**

In [ ]:
a=np.matrix("1,2,3;4,5,6;7,8,9")
print(a)
print(f"number of rows and columns are: {a.shape}")
print("a.shape[0] returns number of rows & a.shape[1] return number of coloumns")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
number of rows and columns are: (3, 3)
a.shape[0] returns number of rows & a.shape[1] return number of coloumns


#**size()**

In [ ]:
a=np.matrix("1,2,3;4,5,6;7,8,9")
print(a)
print(a.size)
print("it returns number of elements present in the matrix")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
it returns number of elements present in the matrix


#**dot operation**

In [ ]:
a=np.matrix("1,2,3;4,5,6;7,8,9")
print(a)
b=np.matrix("9,5,6;7,2,1;0,1,3")
print(b)
c=np.dot(a,b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 5 6]
 [7 2 1]
 [0 1 3]]
[[ 23  12  17]
 [ 71  36  47]
 [119  60  77]]


#**Determinant rank and inverse of matrix**

In [ ]:
a=np.matrix("1,2,3,8;7,4,5,6;-12,7,8,9;5,89,21,4")
print(a)
print(f"determinat is {np.linalg.det(a)}")
print(f"rank is {np.linalg.matrix_rank(a)}")
print(f"inverse is \n {np.linalg.inv(a)}")

[[  1   2   3   8]
 [  7   4   5   6]
 [-12   7   8   9]
 [  5  89  21   4]]
determinat is 36064.00000000003
rank is 4
inverse is 
 [[-0.00424246  0.06973713 -0.04286823  0.00033274]
 [ 0.06616016 -0.06139086 -0.02429015  0.01441881]
 [-0.32323092  0.26095275  0.11950976 -0.01386424]
 [ 0.23020186 -0.09122671 -0.03338509  0.0015528 ]]


#**System of linearequations**

In [ ]:
A=np.matrix("3,1,2;3,2,5;6,7,8")
print(A)
b=np.matrix("2,-1,3").transpose()
print(b)
sol_linear=np.linalg.solve(A,b)
print(sol_linear)

[[3 1 2]
 [3 2 5]
 [6 7 8]]
[[ 2]
 [-1]
 [ 3]]
[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
